from __future__ import annotations

from pathlib import Path


def write_base_domain_caddyfile(target: Path, base_domain: str) -> None:
    if target.exists():
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        f"# Let's Encrypt will issue a wildcard cert for {base_domain} and *.{base_domain}\n"
        "# This file must exist so the panel applies this domain.\n"
        "# import common-tls\n"
    )


def _format_admin_ips(admin_ips: str) -> str:
    parts = []
    for raw in admin_ips.split(","):
        ip = raw.strip()
        if not ip:
            continue
        if "/" not in ip:
            ip = f"{ip}/32"
        parts.append(ip)
    return " ".join(parts)


_JENKINS_OPEN = """# Auto-generated by AlphaPanel installer — DO NOT DELETE
# This file is NOT managed by panel:apply
{jenkins_domain}:443 {{
    tls /etc/letsencrypt/live/{base_domain}/fullchain.pem /etc/letsencrypt/live/{base_domain}/privkey.pem

    handle /__whoami {{
        respond "remote={{http.request.remote.host}}\\nxff={{http.request.header.X-Forwarded-For}}\\ncf={{http.request.header.CF-Connecting-IP}}\\nreal={{http.request.header.X-Real-IP}}\\n"
    }}

    @webhook {{
        path /github-webhook*
        import /etc/frankenphp/_github_hooks_allowlist.caddy
    }}
    handle @webhook {{
        reverse_proxy jenkins:8080
    }}

    handle {{
        reverse_proxy jenkins:8080
    }}
}}
"""

_JENKINS_RESTRICTED = """# Auto-generated by AlphaPanel installer — DO NOT DELETE
# This file is NOT managed by panel:apply
{jenkins_domain}:443 {{
    tls /etc/letsencrypt/live/{base_domain}/fullchain.pem /etc/letsencrypt/live/{base_domain}/privkey.pem

    handle /__whoami {{
        respond "remote={{http.request.remote.host}}\\nxff={{http.request.header.X-Forwarded-For}}\\ncf={{http.request.header.CF-Connecting-IP}}\\nreal={{http.request.header.X-Real-IP}}\\n"
    }}

    @webhook {{
        path /github-webhook*
        import /etc/frankenphp/_github_hooks_allowlist.caddy
    }}
    handle @webhook {{
        reverse_proxy jenkins:8080
    }}

    @admin client_ip {cidr_list}
    handle @admin {{
        reverse_proxy jenkins:8080
    }}

    handle {{
        respond 403
    }}
}}
"""


def write_jenkins_caddyfile(
    target: Path,
    base_domain: str,
    jenkins_domain: str,
    admin_ips: str,
) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    cidrs = _format_admin_ips(admin_ips)
    if cidrs:
        target.write_text(
            _JENKINS_RESTRICTED.format(
                jenkins_domain=jenkins_domain,
                base_domain=base_domain,
                cidr_list=cidrs,
            )
        )
    else:
        target.write_text(
            _JENKINS_OPEN.format(
                jenkins_domain=jenkins_domain,
                base_domain=base_domain,
            )
        )
