from __future__ import annotations

import os
import shutil
from pathlib import Path

_UID_GID_1000_DIRS = ["deploy_cache", "n8n", "backup"]

_DIRS = [
    "secrets",
    "letsencrypt",
    "deploy_cache",
    "backup",
    "portainer",
    "vaultwarden/data",
    "mysql/data",
    "postgres",
    "redis",
    "meilisearch/data",
    "meilisearch/tmp",
    "alpha-panel/meilisearch/data",
    "alpha-panel/meilisearch/tmp",
    "alpha-panel/web/logs",
    "alpha-panel/web/caddy_data",
    "alpha-panel/web/ssl",
    "frankenphp/caddy_data",
    "frankenphp/logs",
    "frankenphp/waf/generated/domains",
    "n8n/data",
    "n8n/files",
    "jenkins/data",
    "code-server/data",
    "external-services",
]


def ensure_data_directories(base: Path, base_domain: str) -> None:
    for rel in _DIRS:
        (base / rel).mkdir(parents=True, exist_ok=True)
    (base / "frankenphp/sites-enabled" / base_domain).mkdir(parents=True, exist_ok=True)

    global_conf = base / "frankenphp/waf/generated/global.conf"
    if not global_conf.exists():
        global_conf.write_text(
            "# Auto-generated by AlphaPanel.\n# (no global IP rules)\n"
        )

    default_domain = base / "frankenphp/waf/generated/domains/000-default.conf"
    if not default_domain.exists():
        default_domain.write_text(
            "# Auto-generated by AlphaPanel.\n# (no domain-specific rules)\n"
        )

    local_services = base / "external-services/local-services.yaml"
    if not local_services.exists():
        local_services.parent.mkdir(parents=True, exist_ok=True)
        local_services.write_text("# Local extra services (git-ignored). Add your own compose services here.\n")

    ftp_users_env = base / "ftp-config/users.env"
    if not ftp_users_env.exists():
        ftp_users_env.parent.mkdir(parents=True, exist_ok=True)
        ftp_users_env.write_text('USERS=""\n')

    _apply_container_ownership(base)


def _apply_container_ownership(base: Path) -> None:
    """
    Container processes run as UID 1000 (n8n, deploy worker, backup writer).
    Without explicit ownership the bind-mounted host paths inherit root:root and
    the containers silently fail to write. POSIX-only — chown is a no-op on Windows.
    """
    if os.name != "posix":
        return

    chown = getattr(shutil, "chown", None)
    if chown is None:
        return

    for rel in _UID_GID_1000_DIRS:
        target = base / rel
        if not target.exists():
            continue

        for path in [target, *target.rglob("*")]:
            try:
                chown(path, user=1000, group=1000)
            except (PermissionError, LookupError):
                pass
            try:
                path.chmod(path.stat().st_mode | 0o770)
            except PermissionError:
                pass
