from __future__ import annotations

from pathlib import Path

_DIRS = [
    "secrets",
    "letsencrypt",
    "deploy_cache",
    "backup",
    "portainer",
    "vaultwarden/data",
    "mysql/data",
    "postgres",
    "redis",
    "meilisearch/data",
    "meilisearch/tmp",
    "alpha-panel/meilisearch/data",
    "alpha-panel/meilisearch/tmp",
    "alpha-panel/web/logs",
    "alpha-panel/web/caddy_data",
    "alpha-panel/web/ssl",
    "frankenphp/caddy_data",
    "frankenphp/logs",
    "frankenphp/waf/generated/domains",
    "n8n/data",
    "n8n/files",
    "jenkins/data",
    "code-server/data",
    "external-services",
]


def ensure_data_directories(base: Path, base_domain: str) -> None:
    for rel in _DIRS:
        (base / rel).mkdir(parents=True, exist_ok=True)
    (base / "frankenphp/sites-enabled" / base_domain).mkdir(parents=True, exist_ok=True)

    global_conf = base / "frankenphp/waf/generated/global.conf"
    if not global_conf.exists():
        global_conf.write_text(
            "# Auto-generated by AlphaPanel.\n# (no global IP rules)\n"
        )

    default_domain = base / "frankenphp/waf/generated/domains/000-default.conf"
    if not default_domain.exists():
        default_domain.write_text(
            "# Auto-generated by AlphaPanel.\n# (no domain-specific rules)\n"
        )
