[program:alphapanel-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /var/www/AlphaPanel/httpdocs/artisan queue:work --daemon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=3
redirect_stderr=true
stdout_logfile=/var/www/AlphaPanel/httpdocs/storage/logs/worker.log
stopwaitsecs=3600
startsecs=0