[program:alphapanel-reverb]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /var/www/AlphaPanel/httpdocs/artisan reverb:start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/www/AlphaPanel/httpdocs/storage/logs/reverb.log
stopwaitsecs=3600
startsecs=0