[program:alphapanel-server-stats]
process_name=%(program_name)s
command=/usr/local/bin/php /var/www/AlphaPanel/httpdocs/artisan system:broadcast-server-stats --interval=15
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/AlphaPanel/httpdocs/storage/logs/server-stats.log
stopwaitsecs=10
startsecs=0
