[program:apache2]
command=/bin/bash -lc "source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"
user=root
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
autorestart=true
startretries=20
priority=20
