;[program:php8.5-fpm]
;command=/usr/sbin/php-fpm8.5 --nodaemonize --fpm-config /etc/php/8.5/fpm/php-fpm.conf
;autorestart=true
;stdout_logfile=/var/log/php8.5-fpm.log
;stderr_logfile=/var/log/php8.5-fpm.err
