<?php

namespace App\Services;

use App\Models\DockerService;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;

class ComposeFileService
{
    /**
     * Regenerate the docker-services.yaml file and ensure it's included.
     */
    public function regenerate(): void
    {
        $this->writeFile();
        $this->ensureIncluded();
    }

    /**
     * Generate compose YAML from all docker services.
     */
    public function generateYaml(): string
    {
        $services = DockerService::all();

        $lines = ['# Auto-generated by AlphaPanel — do not edit manually'];

        if ($services->isEmpty()) {
            $lines[] = 'services: {}';

            return implode("\n", $lines)."\n";
        }

        $lines[] = 'services:';

        foreach ($services as $service) {
            $lines[] = "  {$service->name}:";
            $lines[] = "    image: \"{$service->image}:{$service->tag}\"";
            $lines[] = "    container_name: \"{$service->name}\"";
            $lines[] = "    restart: \"{$service->restart_policy->value}\"";

            if ($service->hostname) {
                $lines[] = "    hostname: \"{$service->hostname}\"";
            }

            // Environment variables
            $envVars = $service->environment_variables ?? [];
            if (! empty($envVars)) {
                $lines[] = '    environment:';
                foreach ($envVars as $key => $value) {
                    $lines[] = "      - \"{$key}={$value}\"";
                }
            }

            // Volumes
            $volumes = $service->volumes ?? [];
            $volumeLines = [];
            $volumeBase = config('panel.docker_services.volume_base_path');
            foreach ($volumes as $vol) {
                $hostPath = $vol['host_path'] ?? "{$volumeBase}/{$service->name}/data";
                $containerPath = $vol['container_path'] ?? '';
                $mode = $vol['mode'] ?? 'rw';
                if ($containerPath) {
                    $volumeLines[] = "      - \"{$hostPath}:{$containerPath}:{$mode}\"";
                }
            }
            if (! empty($volumeLines)) {
                $lines[] = '    volumes:';
                array_push($lines, ...$volumeLines);
            }

            // Ports
            $ports = $service->ports ?? [];
            $portLines = [];
            foreach ($ports as $port) {
                $hostPort = $port['host_port'] ?? 0;
                $containerPort = $port['container_port'] ?? 0;
                $protocol = $port['protocol'] ?? 'tcp';
                if ($hostPort && $containerPort) {
                    $portStr = "{$hostPort}:{$containerPort}";
                    if ($protocol !== 'tcp') {
                        $portStr .= "/{$protocol}";
                    }
                    $portLines[] = "      - \"{$portStr}\"";
                }
            }
            if (! empty($portLines)) {
                $lines[] = '    ports:';
                array_push($lines, ...$portLines);
            }

            // Resource limits
            $limits = $service->resource_limits;
            if (! empty($limits['cpu_limit']) || ! empty($limits['memory_limit'])) {
                $lines[] = '    deploy:';
                $lines[] = '      resources:';
                $lines[] = '        limits:';
                if (! empty($limits['cpu_limit'])) {
                    $lines[] = '          cpus: "'.$limits['cpu_limit'].'"';
                }
                if (! empty($limits['memory_limit'])) {
                    $lines[] = '          memory: "'.$limits['memory_limit'].'"';
                }
            }

            // Networks
            $networks = ['vhost_network'];
            foreach ($service->networks ?? [] as $net) {
                if ($net && $net !== 'vhost_network') {
                    $networks[] = $net;
                }
            }
            $lines[] = '    networks:';
            foreach ($networks as $net) {
                $lines[] = "      - {$net}";
            }
        }

        // Network declaration
        $lines[] = '';
        $lines[] = 'networks:';
        $lines[] = '  vhost_network:';
        $lines[] = '    external: true';

        return implode("\n", $lines)."\n";
    }

    /**
     * Write the compose file to disk.
     */
    public function writeFile(): void
    {
        $path = config('panel.docker_services.compose_path');
        $yaml = $this->generateYaml();

        $dir = dirname($path);
        if (! File::isDirectory($dir)) {
            File::makeDirectory($dir, 0755, true);
        }

        File::put($path, $yaml);

        Log::info("Docker services compose file written: {$path}");
    }

    /**
     * Ensure docker-services.yaml is included in local-services.yaml.
     */
    public function ensureIncluded(): void
    {
        $localServicesPath = config('panel.docker_services.local_services_path');

        if (! File::exists($localServicesPath)) {
            Log::warning("Local services file not found: {$localServicesPath}");

            return;
        }

        $content = File::get($localServicesPath);

        if (str_contains($content, 'docker-services.yaml')) {
            return; // Already included
        }

        // Append the include line
        $content = rtrim($content)."\n  - ./docker-services.yaml\n";
        File::put($localServicesPath, $content);

        Log::info('Added docker-services.yaml to local services include list.');
    }
}
