<?php

namespace App\Services;

use App\Models\DockerService;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;

class ComposeFileService
{
    /**
     * Regenerate all individual service compose files and rebuild the index.
     */
    public function regenerate(): void
    {
        $services = DockerService::all();

        foreach ($services as $service) {
            $this->writeServiceYaml($service);
        }

        $this->rebuildIndex();
        $this->ensureIndexIncluded();
        $this->cleanupLegacyFiles();
    }

    /**
     * Write compose file for a single service and update the aggregator index.
     */
    public function writeServiceFile(DockerService $service): void
    {
        $this->writeServiceYaml($service);
        $this->rebuildIndex();
        $this->ensureIndexIncluded();

        Log::info("Docker service compose file written: {$service->name}");
    }

    /**
     * Remove compose file for a service and update the aggregator index.
     */
    public function removeServiceFile(DockerService $service): void
    {
        $this->removeServiceFileByName($service->name);
    }

    /**
     * Remove compose file by service name and rebuild the index.
     */
    public function removeServiceFileByName(string $serviceName): void
    {
        $path = $this->getServiceFilePath($serviceName);

        if (File::exists($path)) {
            File::delete($path);
            Log::info("Docker service compose file removed: {$path}");
        }

        $this->rebuildIndex();
    }

    /**
     * Generate compose YAML for a single Docker service.
     */
    public function generateServiceYaml(DockerService $service): string
    {
        $lines = ["# Auto-generated by AlphaPanel for service: {$service->name}"];
        $lines[] = 'services:';
        $lines[] = "  {$service->name}:";
        $lines[] = "    image: \"{$service->image}:{$service->tag}\"";
        $lines[] = "    container_name: \"{$service->name}\"";
        $lines[] = "    restart: \"{$service->restart_policy->value}\"";

        if ($service->hostname) {
            $lines[] = "    hostname: \"{$service->hostname}\"";
        }

        // Environment variables
        $envVars = $service->environment_variables ?? [];
        if (! empty($envVars)) {
            $lines[] = '    environment:';
            foreach ($envVars as $key => $value) {
                $lines[] = "      - \"{$key}={$value}\"";
            }
        }

        // Volumes
        $volumes = $service->volumes ?? [];
        $volumeLines = [];
        $volumeBase = config('panel.docker_services.volume_base_path');
        foreach ($volumes as $vol) {
            $hostPath = $vol['host_path'] ?? "{$volumeBase}/{$service->name}/data";
            $containerPath = $vol['container_path'] ?? '';
            $mode = $vol['mode'] ?? 'rw';
            if ($containerPath) {
                $volumeLines[] = "      - \"{$hostPath}:{$containerPath}:{$mode}\"";
            }
        }
        if (! empty($volumeLines)) {
            $lines[] = '    volumes:';
            array_push($lines, ...$volumeLines);
        }

        // Ports
        $ports = $service->ports ?? [];
        $portLines = [];
        foreach ($ports as $port) {
            $hostPort = $port['host_port'] ?? 0;
            $containerPort = $port['container_port'] ?? 0;
            $protocol = $port['protocol'] ?? 'tcp';
            if ($hostPort && $containerPort) {
                $portStr = "{$hostPort}:{$containerPort}";
                if ($protocol !== 'tcp') {
                    $portStr .= "/{$protocol}";
                }
                $portLines[] = "      - \"{$portStr}\"";
            }
        }
        if (! empty($portLines)) {
            $lines[] = '    ports:';
            array_push($lines, ...$portLines);
        }

        // Resource limits
        $limits = $service->resource_limits;
        if (! empty($limits['cpu_limit']) || ! empty($limits['memory_limit'])) {
            $lines[] = '    deploy:';
            $lines[] = '      resources:';
            $lines[] = '        limits:';
            if (! empty($limits['cpu_limit'])) {
                $lines[] = '          cpus: "'.$limits['cpu_limit'].'"';
            }
            if (! empty($limits['memory_limit'])) {
                $lines[] = '          memory: "'.$limits['memory_limit'].'"';
            }
        }

        // Networks
        $networks = ['vhost_network'];
        foreach ($service->networks ?? [] as $net) {
            if ($net && $net !== 'vhost_network') {
                $networks[] = $net;
            }
        }
        $lines[] = '    networks:';
        foreach ($networks as $net) {
            $lines[] = "      - {$net}";
        }

        // Network declaration
        $lines[] = '';
        $lines[] = 'networks:';
        $lines[] = '  vhost_network:';
        $lines[] = '    external: true';

        return implode("\n", $lines)."\n";
    }

    /**
     * Write the YAML file for a service to disk.
     */
    private function writeServiceYaml(DockerService $service): void
    {
        $path = $this->getServiceFilePath($service->name);
        $yaml = $this->generateServiceYaml($service);

        $dir = dirname($path);
        if (! File::isDirectory($dir)) {
            File::makeDirectory($dir, 0755, true);
        }

        File::put($path, $yaml);
    }

    /**
     * Get the file path for a service compose file.
     */
    private function getServiceFilePath(string $serviceName): string
    {
        $dir = config('panel.docker_services.compose_dir');

        return "{$dir}/{$serviceName}.yaml";
    }

    /**
     * Rebuild the aggregator docker-compose.yaml from directory contents.
     *
     * Scans the compose directory for all *.yaml files (excluding the index itself)
     * and generates an include list. This is the single source of truth — whatever
     * files exist in the directory are included automatically.
     */
    private function rebuildIndex(): void
    {
        $dir = config('panel.docker_services.compose_dir');
        $indexPath = "{$dir}/docker-compose.yaml";

        if (! File::isDirectory($dir)) {
            File::makeDirectory($dir, 0755, true);
        }

        // Scan directory for service YAML files (exclude the aggregator itself)
        $files = collect(File::glob("{$dir}/*.yaml"))
            ->map(fn (string $path) => basename($path))
            ->filter(fn (string $name) => $name !== 'docker-compose.yaml')
            ->sort()
            ->values();

        $lines = ['# Auto-generated by AlphaPanel — do not edit manually'];

        if ($files->isEmpty()) {
            $lines[] = 'services: {}';
        } else {
            $lines[] = 'include:';
            foreach ($files as $file) {
                $lines[] = "  - ./{$file}";
            }
        }

        File::put($indexPath, implode("\n", $lines)."\n");

        Log::info("Docker services index rebuilt with {$files->count()} service(s).");
    }

    /**
     * Ensure the aggregator is included in local-services.yaml (one-time setup).
     */
    private function ensureIndexIncluded(): void
    {
        $localServicesPath = config('panel.docker_services.local_services_path');
        $includeLine = './docker-services/docker-compose.yaml';

        if (! File::exists($localServicesPath)) {
            Log::warning("Local services file not found: {$localServicesPath}");

            return;
        }

        $content = File::get($localServicesPath);

        if (str_contains($content, $includeLine)) {
            return; // Already included
        }

        $content = rtrim($content)."\n  - {$includeLine}\n";
        File::put($localServicesPath, $content);

        Log::info('Added docker-services aggregator to local services include list.');
    }

    /**
     * Remove legacy monolithic docker-services.yaml if it exists in the parent directory.
     */
    private function cleanupLegacyFiles(): void
    {
        $parentDir = dirname(config('panel.docker_services.compose_dir'));
        $legacyFile = "{$parentDir}/docker-services.yaml";

        if (! File::exists($legacyFile)) {
            return;
        }

        File::delete($legacyFile);
        Log::info('Removed legacy monolithic docker-services.yaml file.');

        // Also remove the old include line from local-services.yaml
        $localServicesPath = config('panel.docker_services.local_services_path');
        if (File::exists($localServicesPath)) {
            $content = File::get($localServicesPath);
            $content = preg_replace('/\n\s*-\s*\.\/docker-services\.yaml/', '', $content);
            File::put($localServicesPath, $content);
        }
    }
}
