<?php

namespace App\Services;

use App\Models\Domain;
use App\Models\WafGlobalIpRule;
use Illuminate\Support\Facades\File;

class WafRulesService
{
    private string $generatedBasePath;

    private string $generatedDomainsPath;

    public function __construct()
    {
        $composeRoot = rtrim((string) config('panel.compose_project_root', '/docker_compose_project_root'), '/');
        $this->generatedBasePath = $composeRoot.'/frankenphp/waf/generated';
        $this->generatedDomainsPath = $this->generatedBasePath.'/domains';
    }

    public function renderAll(): void
    {
        $this->ensurePaths();
        $this->renderGlobalRules();

        $domains = Domain::query()->where('modsecurity_enabled', true)->get();
        foreach ($domains as $domain) {
            $this->renderDomainRules($domain);
        }
    }

    public function renderGlobalRules(): void
    {
        $this->ensurePaths();

        $rules = WafGlobalIpRule::query()
            ->where('enabled', true)
            ->orderBy('id')
            ->get();

        $allow = [];
        $deny = [];
        foreach ($rules as $rule) {
            if ($rule->action === 'allow') {
                $allow[] = $rule->ip_or_cidr;
            } elseif ($rule->action === 'deny') {
                $deny[] = $rule->ip_or_cidr;
            }
        }

        $lines = [
            '# Auto-generated by AlphaPanel. Do not edit manually.',
            '# Global WAF IP rules',
        ];

        $id = 11000000;
        if (count($allow) > 0) {
            $lines[] = sprintf(
                'SecRule REMOTE_ADDR "@ipMatch %s" "id:%d,phase:1,pass,nolog,ctl:ruleEngine=Off,ctl:auditEngine=Off"',
                implode(',', $allow),
                $id++
            );
        }

        if (count($deny) > 0) {
            $lines[] = sprintf(
                'SecRule REMOTE_ADDR "@ipMatch %s" "id:%d,phase:1,deny,status:403,log,msg:\'Global WAF deny list match\'"',
                implode(',', $deny),
                $id++
            );
        }

        if (count($allow) === 0 && count($deny) === 0) {
            $lines[] = '# (no global IP rules)';
        }

        File::put($this->generatedBasePath.'/global.conf', implode("\n", $lines)."\n");
    }

    public function renderDomainRules(Domain $domain): void
    {
        $this->ensurePaths();

        $fqdn = $domain->fqdn;
        $slug = str_replace('.', '_', $fqdn);
        $filePath = $this->generatedDomainsPath."/{$fqdn}.conf";

        if (! $domain->modsecurity_enabled) {
            if (File::exists($filePath)) {
                File::delete($filePath);
            }

            return;
        }

        $globalRules = WafGlobalIpRule::query()
            ->where('enabled', true)
            ->pluck('ip_or_cidr')
            ->map(fn ($ip) => trim((string) $ip))
            ->filter()
            ->values()
            ->all();
        $globalSet = array_flip($globalRules);

        $allow = collect($domain->modsecurity_ip_allowlist ?? [])
            ->map(fn ($ip) => trim((string) $ip))
            ->filter()
            ->reject(fn ($ip) => isset($globalSet[$ip]))
            ->values()
            ->all();

        $deny = collect($domain->modsecurity_ip_blocklist ?? [])
            ->map(fn ($ip) => trim((string) $ip))
            ->filter()
            ->reject(fn ($ip) => isset($globalSet[$ip]))
            ->values()
            ->all();

        $disabledRuleIds = collect($domain->modsecurity_disabled_rule_ids ?? [])
            ->map(fn ($id) => (int) $id)
            ->filter(fn ($id) => $id > 0)
            ->values()
            ->all();

        $customRules = trim((string) ($domain->modsecurity_custom_rules ?? ''));

        $lines = [
            '# Auto-generated by AlphaPanel. Do not edit manually.',
            "# Domain: {$fqdn}",
            '',
        ];

        $id = 12000000 + (int) $domain->id * 1000;

        if (count($allow) > 0) {
            $lines[] = sprintf(
                'SecRule REQUEST_HEADERS:Host "@rx ^%s$" "id:%d,phase:1,pass,nolog,chain"',
                preg_quote($fqdn, '/'),
                $id++
            );
            $lines[] = sprintf(
                'SecRule REMOTE_ADDR "@ipMatch %s" "ctl:ruleEngine=Off,ctl:auditEngine=Off"',
                implode(',', $allow)
            );
            $lines[] = '';
        }

        if (count($deny) > 0) {
            $lines[] = sprintf(
                'SecRule REQUEST_HEADERS:Host "@rx ^%s$" "id:%d,phase:1,deny,status:403,log,msg:\'Domain WAF deny list match\',chain"',
                preg_quote($fqdn, '/'),
                $id++
            );
            $lines[] = sprintf(
                'SecRule REMOTE_ADDR "@ipMatch %s" ""',
                implode(',', $deny)
            );
            $lines[] = '';
        }

        if (count($disabledRuleIds) > 0) {
            $ctlParts = array_map(
                fn ($ruleId) => "ctl:ruleRemoveById={$ruleId}",
                $disabledRuleIds
            );
            $lines[] = sprintf(
                'SecRule REQUEST_HEADERS:Host "@rx ^%s$" "id:%d,phase:1,pass,nolog,%s"',
                preg_quote($fqdn, '/'),
                $id++,
                implode(',', $ctlParts)
            );
            $lines[] = '';
        }

        if ($customRules !== '') {
            $lines[] = '# Custom rules (domain owner managed)';
            $lines[] = $customRules;
            $lines[] = '';
        }

        if (count($allow) === 0 && count($deny) === 0 && count($disabledRuleIds) === 0 && $customRules === '') {
            $lines[] = '# (no domain-specific rules)';
        }

        File::put($filePath, implode("\n", $lines)."\n");
    }

    private function ensurePaths(): void
    {
        if (! File::isDirectory($this->generatedBasePath)) {
            File::makeDirectory($this->generatedBasePath, 0755, true);
        }

        if (! File::isDirectory($this->generatedDomainsPath)) {
            File::makeDirectory($this->generatedDomainsPath, 0755, true);
        }

        $globalFile = $this->generatedBasePath.'/global.conf';
        if (! File::exists($globalFile)) {
            File::put($globalFile, "# Auto-generated by AlphaPanel.\n# (no global IP rules)\n");
        }

        $defaultDomainFile = $this->generatedDomainsPath.'/000-default.conf';
        if (! File::exists($defaultDomainFile)) {
            File::put($defaultDomainFile, "# Auto-generated by AlphaPanel.\n# (no domain-specific rules)\n");
        }
    }
}
