anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
xferlog_enable=YES
xferlog_std_format=YES
connect_from_port_20=YES
chroot_local_user=YES
allow_writeable_chroot=YES
listen=YES
listen_ipv6=NO
pasv_enable=YES
seccomp_sandbox=NO
log_file=/dev/stdout
ftpd_banner=Welcome to AlphaPanel FTP (FTPS Required)
force_dot_files=YES
require_ssl_reuse=NO
