from __future__ import annotations

import asyncio
import logging
import os
import shutil
import textwrap

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, status
from pydantic import BaseModel

from app.auth import require_auth
from app.config import Settings, get_settings
from app.services.mysql_ops import (
    compare_snapshots,
    export_grants,
    get_mysql_version_from_env,
    get_snapshot,
    import_dump,
    safe_mysqldump,
    set_mysql_version_in_env,
)
from app.services.panel_ops import (
    compose_down,
    compose_stop,
    compose_up,
    run_cmd,
)
from app.services.task_manager import TaskStatus, task_manager

logger = logging.getLogger(__name__)

router = APIRouter(tags=["mysql"])

# Test compose file location (relative to PROJECT_ROOT)
_TEST_COMPOSE_REL = "external-services/mysql-upgrade-test.yaml"

# Ports for the test MySQL and phpMyAdmin containers
_TEST_MYSQL_PORT = 13306
_TEST_PMA_PORT = 18080


class PrepareRequest(BaseModel):
    target_version: str


def _test_compose_path(project_root: str) -> str:
    return os.path.join(project_root, _TEST_COMPOSE_REL)


def _generate_test_compose(
    project_root: str,
    target_version: str,
    test_mysql_port: int = _TEST_MYSQL_PORT,
    test_pma_port: int = _TEST_PMA_PORT,
) -> str:
    """Generate a docker compose YAML for the MySQL upgrade test environment."""
    compose_content = textwrap.dedent(f"""\
        # Auto-generated by AlphaPanel Update Agent -- do not edit manually
        name: mysql-upgrade-test

        services:
          mysql-upgrade-test:
            image: mysql:{target_version}
            container_name: mysql-upgrade-test
            environment:
              MYSQL_ROOT_PASSWORD: ${{MYSQL_ROOT_PASSWORD}}
            ports:
              - "{test_mysql_port}:3306"
            volumes:
              - mysql_upgrade_test_data:/var/lib/mysql
            networks:
              - vhost_network
            healthcheck:
              test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${{MYSQL_ROOT_PASSWORD}}"]
              interval: 5s
              timeout: 5s
              retries: 30
              start_period: 30s

          pma-upgrade-test:
            image: phpmyadmin/phpmyadmin:latest
            container_name: pma-upgrade-test
            environment:
              PMA_HOST: mysql-upgrade-test
              PMA_PORT: 3306
              MYSQL_ROOT_PASSWORD: ${{MYSQL_ROOT_PASSWORD}}
            ports:
              - "{test_pma_port}:80"
            networks:
              - vhost_network
            depends_on:
              mysql-upgrade-test:
                condition: service_healthy

        volumes:
          mysql_upgrade_test_data:

        networks:
          vhost_network:
            external: true
    """)
    return compose_content


async def _wait_for_mysql_ready(
    host: str,
    port: int,
    password: str,
    timeout_secs: int = 120,
) -> bool:
    """Poll until MySQL accepts connections or timeout."""
    for _ in range(timeout_secs // 3):
        result = await run_cmd(
            f"mysqladmin ping -h {host} -P {port} -u root -p'{password}' --connect-timeout=3",
            timeout=10,
        )
        if result.ok and "alive" in result.stdout.lower():
            return True
        await asyncio.sleep(3)
    return False


async def _perform_prepare(task_id: str, target_version: str, settings: Settings) -> None:
    """Execute the MySQL upgrade preparation sequence."""
    project_root = settings.project_root
    password = settings.mysql_root_password
    host = settings.mysql_host
    port = settings.mysql_port
    dump_dir = os.path.join(project_root, "mysql", "upgrade-staging")
    dump_path = os.path.join(dump_dir, "full-dump.sql")
    grants_path = os.path.join(dump_dir, "grants.sql")
    test_compose = _test_compose_path(project_root)

    try:
        # Phase 1: Pre-flight checks
        task_manager.update_task(task_id, 5, "Running pre-flight checks", TaskStatus.IN_PROGRESS)

        # Check disk space
        result = await run_cmd(
            f"df -BG {project_root} --output=avail | tail -1",
            timeout=10,
        )
        if result.ok:
            avail_str = result.stdout.strip().rstrip("G")
            try:
                avail_gb = int(avail_str)
                if avail_gb < 5:
                    task_manager.update_task(
                        task_id, 5,
                        f"Insufficient disk space: {avail_gb}GB available, need at least 5GB",
                        TaskStatus.FAILED,
                    )
                    return
            except ValueError:
                logger.warning("Could not parse disk space: %s", result.stdout)

        # Take pre-upgrade snapshot
        task_manager.update_task(task_id, 10, "Taking pre-upgrade database snapshot", TaskStatus.IN_PROGRESS)
        before_snapshot = await get_snapshot(host, port, "root", password)

        # Save snapshot info for later comparison
        os.makedirs(dump_dir, exist_ok=True)

        import json
        snapshot_path = os.path.join(dump_dir, "before-snapshot.json")
        with open(snapshot_path, "w", encoding="utf-8") as f:
            json.dump(before_snapshot, f, indent=2)

        # Phase 2: mysqldump
        task_manager.update_task(task_id, 20, "Creating full database dump (this may take a while)", TaskStatus.IN_PROGRESS)
        result = await safe_mysqldump(host, port, "root", password, dump_path)
        if not result.ok:
            task_manager.update_task(
                task_id, 20,
                f"mysqldump failed: {result.stderr}",
                TaskStatus.FAILED,
            )
            return

        # Export grants
        task_manager.update_task(task_id, 30, "Exporting user grants", TaskStatus.IN_PROGRESS)
        result = await export_grants(host, port, "root", password, grants_path)
        if not result.ok:
            task_manager.update_task(
                task_id, 30,
                f"Grant export failed: {result.stderr}",
                TaskStatus.FAILED,
            )
            return

        # Phase 3: Generate and start test compose
        task_manager.update_task(task_id, 35, "Generating test environment configuration", TaskStatus.IN_PROGRESS)
        compose_content = _generate_test_compose(project_root, target_version)
        os.makedirs(os.path.dirname(test_compose), exist_ok=True)
        with open(test_compose, "w", encoding="utf-8") as f:
            f.write(compose_content)

        task_manager.update_task(task_id, 40, "Starting test MySQL container", TaskStatus.IN_PROGRESS)
        result = await compose_up([], project_root, compose_file=test_compose)
        if not result.ok:
            task_manager.update_task(
                task_id, 40,
                f"Failed to start test containers: {result.stderr}",
                TaskStatus.FAILED,
            )
            return

        # Wait for test MySQL to be ready
        task_manager.update_task(task_id, 45, "Waiting for test MySQL to be ready", TaskStatus.IN_PROGRESS)
        ready = await _wait_for_mysql_ready("127.0.0.1", _TEST_MYSQL_PORT, password, timeout_secs=120)
        if not ready:
            task_manager.update_task(
                task_id, 45,
                "Test MySQL container failed to become ready within 120s",
                TaskStatus.FAILED,
            )
            await compose_down(test_compose, project_root)
            return

        # Import dump into test container
        task_manager.update_task(task_id, 55, "Importing database dump into test container", TaskStatus.IN_PROGRESS)
        result = await import_dump("127.0.0.1", _TEST_MYSQL_PORT, "root", password, dump_path)
        if not result.ok:
            task_manager.update_task(
                task_id, 55,
                f"Dump import failed: {result.stderr}",
                TaskStatus.FAILED,
            )
            await compose_down(test_compose, project_root)
            return

        # Import grants
        task_manager.update_task(task_id, 65, "Importing user grants into test container", TaskStatus.IN_PROGRESS)
        grants_result = await run_cmd(
            f"mysql -h 127.0.0.1 -P {_TEST_MYSQL_PORT} -u root -p'{password}' < {grants_path}",
            timeout=60,
        )
        if not grants_result.ok:
            logger.warning("Grant import had warnings (non-fatal): %s", grants_result.stderr)

        await run_cmd(
            f"mysql -h 127.0.0.1 -P {_TEST_MYSQL_PORT} -u root -p'{password}' -e 'FLUSH PRIVILEGES'",
            timeout=15,
        )

        # Compare snapshots
        task_manager.update_task(task_id, 80, "Comparing database snapshots", TaskStatus.IN_PROGRESS)
        after_snapshot = await get_snapshot("127.0.0.1", _TEST_MYSQL_PORT, "root", password)
        mismatches = compare_snapshots(before_snapshot, after_snapshot)

        if mismatches:
            mismatch_text = "; ".join(mismatches[:5])
            task_manager.update_task(
                task_id, 90,
                f"Verification found {len(mismatches)} discrepancies: {mismatch_text}. "
                "Test environment is still running for manual inspection. "
                f"phpMyAdmin available at port {_TEST_PMA_PORT}.",
                TaskStatus.COMPLETED,
            )
        else:
            task_manager.update_task(
                task_id, 100,
                f"Preparation complete. All {len(before_snapshot.get('databases', []))} databases verified. "
                f"Test environment running on port {_TEST_MYSQL_PORT}. "
                f"phpMyAdmin available at port {_TEST_PMA_PORT}. "
                "Ready for /upgrade/mysql/apply.",
                TaskStatus.COMPLETED,
            )

    except Exception as exc:
        logger.exception("MySQL upgrade preparation failed")
        task_manager.update_task(
            task_id, 0, f"Unexpected error: {exc}", TaskStatus.FAILED
        )
        # Cleanup test containers on failure
        try:
            if os.path.exists(test_compose):
                await compose_down(test_compose, project_root)
        except Exception:
            pass


async def _perform_apply(task_id: str, settings: Settings) -> None:
    """Apply the MySQL upgrade: stop production, swap data, start with new version."""
    project_root = settings.project_root
    password = settings.mysql_root_password
    test_compose = _test_compose_path(project_root)
    mysql_data_dir = os.path.join(project_root, "mysql", "data")
    mysql_backup_dir = os.path.join(project_root, "mysql", "data-backup")
    staging_dir = os.path.join(project_root, "mysql", "upgrade-staging")

    try:
        # Read target version from the test compose file
        if not os.path.exists(test_compose):
            task_manager.update_task(
                task_id, 0,
                "No test environment found. Run /upgrade/mysql/prepare first.",
                TaskStatus.FAILED,
            )
            return

        # Read the target version from the test compose
        with open(test_compose, "r", encoding="utf-8") as f:
            content = f.read()
        import re
        match = re.search(r"image:\s*mysql:(\S+)", content)
        target_version = match.group(1) if match else "unknown"

        # Phase 5: Apply the upgrade
        task_manager.update_task(task_id, 10, "Stopping test containers", TaskStatus.IN_PROGRESS)
        await compose_down(test_compose, project_root)

        task_manager.update_task(task_id, 20, "Stopping production MySQL", TaskStatus.IN_PROGRESS)
        result = await compose_stop(["mysql"], project_root)
        if not result.ok:
            task_manager.update_task(
                task_id, 20,
                f"Failed to stop production MySQL: {result.stderr}",
                TaskStatus.FAILED,
            )
            return

        # Backup current data directory
        task_manager.update_task(task_id, 30, "Backing up current MySQL data directory", TaskStatus.IN_PROGRESS)
        if os.path.exists(mysql_backup_dir):
            shutil.rmtree(mysql_backup_dir)

        if os.path.exists(mysql_data_dir):
            result = await run_cmd(
                f"mv {mysql_data_dir} {mysql_backup_dir}",
                timeout=300,
            )
            if not result.ok:
                task_manager.update_task(
                    task_id, 30,
                    f"Failed to backup data directory: {result.stderr}",
                    TaskStatus.FAILED,
                )
                # Try to restart MySQL with old data
                await compose_up(["mysql"], project_root)
                return

        # Update .env with new MySQL version
        task_manager.update_task(task_id, 45, f"Updating MYSQL_VERSION to {target_version}", TaskStatus.IN_PROGRESS)
        old_version = get_mysql_version_from_env(project_root)
        set_mysql_version_in_env(project_root, target_version)

        # Save the old version for potential rollback
        old_version_path = os.path.join(staging_dir, "old-version.txt")
        os.makedirs(staging_dir, exist_ok=True)
        with open(old_version_path, "w", encoding="utf-8") as f:
            f.write(old_version)

        # Start MySQL with new version (fresh data dir -- will initialize)
        task_manager.update_task(task_id, 55, "Starting MySQL with new version", TaskStatus.IN_PROGRESS)
        result = await compose_up(["mysql"], project_root, force_recreate=True)
        if not result.ok:
            task_manager.update_task(
                task_id, 55,
                f"Failed to start MySQL {target_version}: {result.stderr}",
                TaskStatus.FAILED,
            )
            return

        # Wait for new MySQL to be ready
        task_manager.update_task(task_id, 60, "Waiting for new MySQL to be ready", TaskStatus.IN_PROGRESS)
        ready = await _wait_for_mysql_ready(
            settings.mysql_host, settings.mysql_port, password, timeout_secs=120,
        )
        if not ready:
            task_manager.update_task(
                task_id, 60,
                "New MySQL failed to start. Use /upgrade/mysql/rollback to restore.",
                TaskStatus.FAILED,
            )
            return

        # Import the dump
        dump_path = os.path.join(staging_dir, "full-dump.sql")
        grants_path = os.path.join(staging_dir, "grants.sql")

        task_manager.update_task(task_id, 70, "Importing database dump into new MySQL", TaskStatus.IN_PROGRESS)
        result = await import_dump(
            settings.mysql_host, settings.mysql_port, "root", password, dump_path,
        )
        if not result.ok:
            task_manager.update_task(
                task_id, 70,
                f"Dump import failed: {result.stderr}. Use /upgrade/mysql/rollback to restore.",
                TaskStatus.FAILED,
            )
            return

        # Import grants
        task_manager.update_task(task_id, 80, "Importing user grants", TaskStatus.IN_PROGRESS)
        await run_cmd(
            f"mysql -h {settings.mysql_host} -P {settings.mysql_port} "
            f"-u root -p'{password}' < {grants_path}",
            timeout=60,
        )
        await run_cmd(
            f"mysql -h {settings.mysql_host} -P {settings.mysql_port} "
            f"-u root -p'{password}' -e 'FLUSH PRIVILEGES'",
            timeout=15,
        )

        # Verify
        task_manager.update_task(task_id, 90, "Verifying upgraded database", TaskStatus.IN_PROGRESS)

        import json
        snapshot_path = os.path.join(staging_dir, "before-snapshot.json")
        if os.path.exists(snapshot_path):
            with open(snapshot_path, "r", encoding="utf-8") as f:
                before_snapshot = json.load(f)
            after_snapshot = await get_snapshot(
                settings.mysql_host, settings.mysql_port, "root", password,
            )
            mismatches = compare_snapshots(before_snapshot, after_snapshot)
            if mismatches:
                mismatch_text = "; ".join(mismatches[:5])
                logger.warning("Post-upgrade verification found issues: %s", mismatch_text)

        # Cleanup test compose file
        if os.path.exists(test_compose):
            os.remove(test_compose)

        task_manager.update_task(
            task_id, 100,
            f"MySQL upgraded to {target_version} successfully. "
            "Old data backed up in mysql/data-backup. "
            "Run /upgrade/mysql/cleanup when satisfied.",
            TaskStatus.COMPLETED,
        )

    except Exception as exc:
        logger.exception("MySQL upgrade apply failed")
        task_manager.update_task(
            task_id, 0, f"Unexpected error: {exc}", TaskStatus.FAILED
        )


async def _perform_rollback(task_id: str, settings: Settings) -> None:
    """Rollback a failed MySQL upgrade."""
    project_root = settings.project_root
    mysql_data_dir = os.path.join(project_root, "mysql", "data")
    mysql_backup_dir = os.path.join(project_root, "mysql", "data-backup")
    staging_dir = os.path.join(project_root, "mysql", "upgrade-staging")
    old_version_path = os.path.join(staging_dir, "old-version.txt")

    try:
        # Read old version
        task_manager.update_task(task_id, 10, "Reading previous version info", TaskStatus.IN_PROGRESS)
        old_version = "unknown"
        if os.path.exists(old_version_path):
            with open(old_version_path, "r", encoding="utf-8") as f:
                old_version = f.read().strip()

        # Stop current MySQL
        task_manager.update_task(task_id, 20, "Stopping MySQL", TaskStatus.IN_PROGRESS)
        await compose_stop(["mysql"], project_root)

        # Remove failed data directory
        task_manager.update_task(task_id, 35, "Removing failed upgrade data", TaskStatus.IN_PROGRESS)
        if os.path.exists(mysql_data_dir):
            result = await run_cmd(f"rm -rf {mysql_data_dir}", timeout=300)
            if not result.ok:
                task_manager.update_task(
                    task_id, 35,
                    f"Failed to remove data directory: {result.stderr}",
                    TaskStatus.FAILED,
                )
                return

        # Restore backup
        task_manager.update_task(task_id, 50, "Restoring backup data directory", TaskStatus.IN_PROGRESS)
        if not os.path.exists(mysql_backup_dir):
            task_manager.update_task(
                task_id, 50,
                "No backup directory found at mysql/data-backup. Manual recovery required.",
                TaskStatus.FAILED,
            )
            return

        result = await run_cmd(
            f"mv {mysql_backup_dir} {mysql_data_dir}",
            timeout=300,
        )
        if not result.ok:
            task_manager.update_task(
                task_id, 50,
                f"Failed to restore backup: {result.stderr}",
                TaskStatus.FAILED,
            )
            return

        # Revert .env
        task_manager.update_task(task_id, 70, f"Reverting MYSQL_VERSION to {old_version}", TaskStatus.IN_PROGRESS)
        if old_version != "unknown":
            set_mysql_version_in_env(project_root, old_version)

        # Start MySQL with old version
        task_manager.update_task(task_id, 85, "Starting MySQL with previous version", TaskStatus.IN_PROGRESS)
        result = await compose_up(["mysql"], project_root, force_recreate=True)
        if not result.ok:
            task_manager.update_task(
                task_id, 85,
                f"Failed to start MySQL: {result.stderr}",
                TaskStatus.FAILED,
            )
            return

        # Wait for ready
        ready = await _wait_for_mysql_ready(
            settings.mysql_host, settings.mysql_port, settings.mysql_root_password,
            timeout_secs=120,
        )
        if not ready:
            task_manager.update_task(
                task_id, 90,
                "MySQL started but did not become ready within 120s. Check logs manually.",
                TaskStatus.FAILED,
            )
            return

        task_manager.update_task(
            task_id, 100,
            f"Rollback complete. MySQL restored to version {old_version}.",
            TaskStatus.COMPLETED,
        )

    except Exception as exc:
        logger.exception("MySQL rollback failed")
        task_manager.update_task(
            task_id, 0, f"Unexpected error during rollback: {exc}", TaskStatus.FAILED
        )


@router.post("/upgrade/mysql/prepare", dependencies=[Depends(require_auth)])
async def prepare_mysql_upgrade(
    body: PrepareRequest,
    background_tasks: BackgroundTasks,
    settings: Settings = Depends(get_settings),
) -> dict:
    """Prepare a MySQL major version upgrade.

    Creates a full database dump, starts a test MySQL container with the target
    version, imports the dump, and compares snapshots to verify data integrity.
    """
    task_id = task_manager.create_task()
    background_tasks.add_task(_perform_prepare, task_id, body.target_version, settings)
    return {"task_id": task_id}


@router.post("/upgrade/mysql/apply", dependencies=[Depends(require_auth)])
async def apply_mysql_upgrade(
    background_tasks: BackgroundTasks,
    settings: Settings = Depends(get_settings),
) -> dict:
    """Apply the prepared MySQL upgrade to production.

    Stops production MySQL, backs up data, starts with new version, imports dump,
    and verifies. The old data is preserved in mysql/data-backup for rollback.
    """
    test_compose = _test_compose_path(settings.project_root)
    if not os.path.exists(test_compose):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No prepared upgrade found. Run /upgrade/mysql/prepare first.",
        )

    task_id = task_manager.create_task()
    background_tasks.add_task(_perform_apply, task_id, settings)
    return {"task_id": task_id}


@router.post("/upgrade/mysql/rollback", dependencies=[Depends(require_auth)])
async def rollback_mysql_upgrade(
    background_tasks: BackgroundTasks,
    settings: Settings = Depends(get_settings),
) -> dict:
    """Rollback a failed MySQL upgrade by restoring the backed-up data directory."""
    backup_dir = os.path.join(settings.project_root, "mysql", "data-backup")
    if not os.path.exists(backup_dir):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No backup found at mysql/data-backup. Nothing to rollback to.",
        )

    task_id = task_manager.create_task()
    background_tasks.add_task(_perform_rollback, task_id, settings)
    return {"task_id": task_id}


@router.post("/upgrade/mysql/cleanup", dependencies=[Depends(require_auth)])
async def cleanup_mysql_upgrade(
    settings: Settings = Depends(get_settings),
) -> dict:
    """Remove MySQL upgrade backup and staging files after a successful upgrade."""
    backup_dir = os.path.join(settings.project_root, "mysql", "data-backup")
    staging_dir = os.path.join(settings.project_root, "mysql", "upgrade-staging")
    test_compose = _test_compose_path(settings.project_root)

    removed: list[str] = []

    if os.path.exists(backup_dir):
        shutil.rmtree(backup_dir)
        removed.append("mysql/data-backup")

    if os.path.exists(staging_dir):
        shutil.rmtree(staging_dir)
        removed.append("mysql/upgrade-staging")

    if os.path.exists(test_compose):
        # Ensure test containers are down first
        await compose_down(test_compose, settings.project_root)
        os.remove(test_compose)
        removed.append(_TEST_COMPOSE_REL)

    return {
        "status": "ok",
        "removed": removed,
    }
